name: Create Papyrus Header Generator Package

on:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  validate_and_publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: pwsh

      # Extract version from the tag
      - name: Extract version from tag
        id: version_extraction
        run: |
          if ($env:GITHUB_REF -match '\d+\.\d+\.\d+.*') {
            $versionTag = $matches[0]
            Add-Content -Path $env:GITHUB_ENV -Value "VERSION_TAG=$versionTag"
          } else {
            Write-Error "No valid version found in GITHUB_REF: $env:GITHUB_REF"
          }
        shell: pwsh    

      - name: Show TAG Version
        run: | 
          Write-Host "VERSION_TAG=$env:VERSION_TAG"
        shell: pwsh

      - name: Create archive directories
        run: |
          if (Test-Path "archive") {
            Remove-Item -Path "archive" -Recurse -Force
          }
          New-Item -ItemType Directory -Path "archive/Papyrus_Header_Generator" -Force
        shell: pwsh
      
      - name: Compile Papyrus Header Generator
        run: |
          pyinstaller --onefile --noconfirm papyrus_header_generator.py
        shell: pwsh

      - name: Copy files to archive
        run: |
          # Copy source scripts
          Copy-Item -Path "dist\papyrus_header_generator.exe" -Destination "archive/Papyrus_Header_Generator\" -Force
          Copy-Item -Path "examples\generate-papyrus-headers.bat" -Destination "archive/Papyrus_Header_Generator\" -Force
          Copy-Item -Path "examples\compiled\generate-papyrus-headers.ps1" -Destination "archive/Papyrus_Header_Generator\" -Force
        shell: pwsh

      # Archive dist directory with version tag
      - name: Archive dist directory
        run: |
          $archiveName = "Papyrus_Header_Generator"
          if ($env:VERSION_TAG) {
            $archiveName = "Papyrus_Header_Generator_$env:VERSION_TAG"
          }
          Write-Host "Creating archive: $archiveName.zip"
          Set-Location -Path ./archive
          tar --format zip -cf "$archiveName.zip" "Papyrus_Header_Generator"
          Set-Location -Path ..
        shell: pwsh

      # Upload artifact with version tag
      - name: Upload artifact
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          $archiveName = "Papyrus_Header_Generator"
          if ($env:VERSION_TAG) {
            $archiveName = "Papyrus_Header_Generator_$env:VERSION_TAG"
          }
          gh release upload ${{github.event.release.tag_name}} "./archive/$archiveName.zip"
        shell: pwsh